### ISSUE TITLE
Machine-readable autograder output

### ISSUE THREAD

**Issue by danwallach** [RiceComp215-Staff/RiceChecks#12]
Make a flag to write autograder *output* to a file (YAML? JSON?) suitable for uploading elsewhere. Seems as good an interface for others to do uploads as anything.

**Comment by danwallach** [comment]
Done!

**Comment by danwallach** [comment]
Okay, not done so fast. Let's get more detail in there. Here's a draft from Benjamin:

```yaml
projectName: "RPN"
description: "Simple RPN Calculator"
allPassing: false
points: 0.0
maxPoints: 10.0
results:
- passes: false
  points: 0.0
  maxPoints: 6.0
  title: "Correctness: 0 of 2 tests passed"
  deductions:
  - description: "edu.rice.rpn.RpnCalcTest.testBasicArithmetic: failed"
    cost: 3.0
    test: "edu.rice.rpn.RpnCalcTest.testBasicArithmetic"
  - description: "edu.rice.rpn.RpnCalcTest.testStackHandling: failed"
    cost: 3.0
    test: "edu.rice.rpn.RpnCalcTest.testStackHandling"
- passes: false
  points: 0.0
  maxPoints: 1.0
  title: "Warning / style deductions"
  deductions:
  - description: "CheckStyle (main): 0 of 1 files passed"
    cost: 1.0
    type: "checkstyle"
    section: "main"
    passed: 0
    checked: 1
  - description: "CheckStyle (test): 1 of 1 files passed"
    cost: 0.0
    type: "checkstyle"
    section: "test"
    passed: 1
    checked: 1
  - description: "GoogleJavaFormat: 1 of 2 files passed"
    cost: 1.0
    type: "googlejavaformat"
    passed: 1
    checked: 2
  - description: "Compiler: No warnings or errors"
    cost: 0.0
    type: "javac"
- passes: false
  points: 0.0
  maxPoints: 3.0
  title: "Classes with coverage below 90% (by line) requirement"
  deductions:
  - description: "Coverage of edu.rice.rpn.RpnCalc: 71.1%"
    cost: 0.0
    class: "edu.rice.rpn.RpnCalc"
    coverage: 71.1
```
